### ISSUE TITLE
cannot install nfs-ganesha 2.5.2 on debian stretch (Proxmox 5)

### ISSUE THREAD

**Issue by mamisoa** [nfs-ganesha/nfs-ganesha-debian#11]
Hi,

Here's the error code after trying to install nfs-ganesha & nfs-ganesha-gluster:
`Setting up nfs-ganesha (2.5.2-1) ...
Created symlink /etc/systemd/system/multi-user.target.wants/nfs-ganesha.service → /lib/systemd/system/nfs-ganesha.service.
Failed to preset unit: File nfs-ganesha.service.debian8.service: No such file or directory
/usr/bin/deb-systemd-helper: error: systemctl preset failed on nfs-ganesha.service.debian8: No such file or directory
Failed to preset unit: File nfs-ganesha.service.el7.service: No such file or directory
/usr/bin/deb-systemd-helper: error: systemctl preset failed on nfs-ganesha.service.el7: No such file or directory
nfs-ganesha-config.service is a disabled or a static unit, not starting it.
Failed to get unit file state for nfs-ganesha-config.service-in.cmake.service: No such file or directory
nfs-ganesha-config.service-in.cmake is a disabled or a static unit, not starting it.
nfs-ganesha-lock.service is a disabled or a static unit, not starting it.
Failed to get unit file state for nfs-ganesha.service.debian8.service: No such file or directory
nfs-ganesha.service.debian8 is a disabled or a static unit, not starting it.
Failed to get unit file state for nfs-ganesha.service.el7.service: No such file or directory
nfs-ganesha.service.el7 is a disabled or a static unit, not starting it.
Setting up nfs-ganesha-gluster:amd64 (2.5.2-1) ...
Processing triggers for libc-bin (2.24-11+deb9u1) ...
Processing triggers for dbus (1.10.18-1) ...
`
Any clue?

Tx , Mike

**Comment by malahal** [comment]
upstream ganesha has split the nfs-ganesha.service file for rpms and deb based systems. Looks like the debian build files (debian/rules file in particular) needs fixing before building debian packages. Just a guess...

**Comment by kalebskeithley** [comment]
fixed in 2.5.3 packages
