### ISSUE TITLE
nfs-ganesha packages for Ubuntu Trusty LTS missing

### ISSUE THREAD

**Issue by earlruby** [nfs-ganesha/nfs-ganesha-debian#13]
When you changed the PPA from http://ppa.launchpad.net/gluster/nfs-ganesha/ubuntu to http://ppa.launchpad.net/gluster/nfs-ganesha-2.5/ubuntu you dropped all of the Trusty packages. Gluster 3.10 LTS is still supporting Trusty, but I can't get Ganesha 2.4 or 2.5 packages that will work with it.

**Comment by kalebskeithley** [comment]
there are nfs-ganesha-2.5.3 packages there for trusty now.
