### ISSUE TITLE
Unsatisfied dependency on libntirpc1 in nfs-ganesha 2.5.5

### ISSUE THREAD

**Issue by Mobo0** [nfs-ganesha/nfs-ganesha-debian#16]
PPAs for libntirpc1 on Ubuntu 16.04 (xenial) have been updated to 1.5.4, and 1.5.3 has been removed. After updating the system, starting nfs-ganesha 2.5.5 now fails with the following error:

/usr/bin/ganesha.nfsd: /lib/x86_64-linux-gnu/libntirpc.so.1.5: version `NTIRPC_1.5.3' not found (required by /usr/bin/ganesha.nfsd)

Running strings on ganesha.nfsd shows NTIRPC_1.5.3 is hard coded in the binary. The dependency test is probably for the explicit version of libntirpc, when it would be more robust to test for the minimum acceptable version.

**Comment by kalebskeithley** [comment]
I have respun the nfs-ganesha packages and examined /usr/bin/ganesha.nfsd to ensure that it uses libntirpc-1.5.4.

Yes, the libntirpc build process puts a version symbol (NTIRPC_1.5.4) in the library and when linked with the library ganesha.nfsd then requires that symbol to be there.

That's a libntirpc build thing, nothing to do with the packaging or these packaging files. If you think thatt the version symbol is not necessary you should open an issue in the nfs-ganesha/ntirpc issue tracker.

thanks
