### ISSUE TITLE
Start/manage service

### ISSUE THREAD

**Issue by strarsis** [nfs-ganesha/nfs-ganesha-debian#17]
@kalebskeithley: I successfully installed nfs-ganesha package (launchpad PPA).
How can I start ganesha-nfs as service on Debian/Ubuntu? Can I find its service under a specific name?

**Comment by malahal** [comment]
I thought ubuntu starts the service by default, it depends on the packaging
though. The systemd service unit file name is nfs-ganesha.service, so the
service  "nfs-ganesha" should be available.

Regards, Malahal.

**Comment by kalebskeithley** [comment]
The nfs-ganesha.service file is installed in /lib/systemd/system/...

Use the systemctl(1) utility to enable and/or start nfs-ganesha. (Exactly the same as Fedora, CentOS, RHEL, and any other distribution that uses systemd.)

**Comment by strarsis** [comment]
@kalebskeithley: In this case I want to run it on WSL (Bash on Windows) because it misses kernel-level file system support, notably for NFS and FUSE. In WSL I can use `service` command.

**Comment by kalebskeithley** [comment]
I have no idea how this might work on WSL. If WSL uses Ubuntu packages I would expect it to work the same as it does on Ubuntu.
`service foo start` is old sysv init.d.  The Systemd way uses `systemctl enable nfs-ganesha` and `systemctl start nfs-ganesha`
