### ISSUE TITLE
Missing file libfsalgluster.so

### ISSUE THREAD

**Issue by ssirag** [nfs-ganesha/nfs-ganesha-debian#18]
I have a working GlusterFS 3.13 configuration on Ubuntu 16.04.  I'm trying to enable nfs-ganesha.  I've installed libntirpc-1.6 and nfs-ganesha-2.6 from these PPA's, using apt install libntirpc1 and apt install nfs-ganesha:

https://launchpad.net/~gluster/+archive/ubuntu/libntirpc-1.6
https://launchpad.net/~gluster/+archive/ubuntu/nfs-ganesha-2.6

I've configured an export file (see bottom).

The nfs-ganesha service starts, but the following error appears to derail the export...

From ganesha log file:
NFS STARTUP :CRIT :Could not dlopen module:/usr/lib/x86_64-linux-gnu/ganesha/libfsalgluster.so Error:/usr/lib/x86_64-linux-gnu/ganesha/libfsalgluster.so: cannot open shared object file: No such file or directory

/etc/ganesha/ganesha.conf:
EXPORT{
    Export_Id = 1 ;   # Export ID unique to each export
    Path = "/gvol1";  # Path of the volume to be exported. Eg: "/test_volume"

    FSAL {
        name = "GLUSTER";
        hostname = "10.0.10.7";  # IP of one of the nodes in the trusted pool
        volume = "gvol1";  # Volume name. Eg: "test_volume"
    }

    Access_type = RW;    # Access permissions
    Squash = No_root_squash; # To enable/disable root squashing
    Disable_ACL = TRUE;  # To enable/disable ACL
    Pseudo = "/gvol1";  # NFSv4 pseudo path for this export. Eg: "/test_volume_pseudo"
    Protocols = "3","4" ;    # NFS protocols supported
    Transports = "UDP","TCP" ; # Transport protocols supported
    SecType = "sys";     # Security flavors supported
}

**Comment by kalebskeithley** [comment]
Install nfs-ganesha-gluster from the PPA

**Comment by ssirag** [comment]
that worked, thanks!
