### ISSUE TITLE
split nfs-ganesha-fsal

### ISSUE THREAD

**Issue by ktdreyer** [nfs-ganesha/nfs-ganesha-debian#2]
It would be nice if the Debian packaging split up the FSALs into individual sub-packages so you could see what exactly is available. This would also lead to smaller containers and bring Debian into parity with the Fedora nfs-ganesha FSAL packaging.

**Comment by hunter** [comment]
This sounds like a great idea. I'd raised an [issue](https://github.com/ceph/ceph-docker/issues/384) last week regarding the inclusion of Ceph in the packages so useful addition to avoid confusion about what's included while keeping the package size down
