### ISSUE TITLE
Packages for Jessie?

### ISSUE THREAD

**Issue by Boran** [nfs-ganesha/nfs-ganesha-debian#21]
Hi,

I've a debian 8 server which mounts files via cephfs and reexports via NFS. When mounting via a NFS client I get "stale" errors (although no files have been moved). 

This is probably because a ceph backend for NFS need a package such as nfs-ganesha-debian to work, is that right?
If so where can one find packages for Debian8/jessie? On https://packages.debian.org/search?keywords=nfs-ganesha there are only packages for stretch available.

**Comment by kalebskeithley** [comment]
download.nfs-ganesha.org. There are ganesha-2.5.x packages for jessie, but there is no nfs-ganesha-ceph (FSAL_CEPH) because the Ceph in jessie is too old.
