### ISSUE TITLE
Logrotate for ganesha-gfapi.log

### ISSUE THREAD

**Issue by ryno83** [nfs-ganesha/nfs-ganesha-debian#22]
The DEB package is missing the logrotate configuration file. Also missing on 2.6.x packages. I'm on debian stretch. I didn't test on other Debian/Ubuntu releases.

**dpkg -c nfs-ganesha-gluster_2.7.0-1_amd64.deb**

drwxr-xr-x root/root 0 2018-09-21 07:51 ./
drwxr-xr-x root/root 0 2018-09-21 07:51 ./etc/
drwxr-xr-x root/root 0 2018-09-21 07:51 ./etc/ganesha/
-rw-r--r-- root/root 822 2018-09-21 07:51 ./etc/ganesha/gluster.conf
drwxr-xr-x root/root 0 2018-09-21 07:51 ./usr/
drwxr-xr-x root/root 0 2018-09-21 07:51 ./usr/lib/
drwxr-xr-x root/root 0 2018-09-21 07:51 ./usr/lib/x86_64-linux-gnu/
drwxr-xr-x root/root 0 2018-09-21 07:51 ./usr/lib/x86_64-linux-gnu/ganesha/
-rw-r--r-- root/root 85672 2018-09-21 07:51 ./usr/lib/x86_64-linux-gnu/ganesha/libfsalgluster.so
drwxr-xr-x root/root 0 2018-09-21 07:51 ./usr/share/
drwxr-xr-x root/root 0 2018-09-21 07:51 ./usr/share/doc/
drwxr-xr-x root/root 0 2018-09-21 07:51 ./usr/share/doc/nfs-ganesha-gluster/
-rw-r--r-- root/root 6518 2018-09-21 07:40 ./usr/share/doc/nfs-ganesha-gluster/changelog.Debian.gz
-rw-r--r-- root/root 1299 2018-09-21 07:39 ./usr/share/doc/nfs-ganesha-gluster/copyright

**Comment by kalebskeithley** [comment]
fixed in 2.6.3-2 and 2.7.0-2 pkgs on download.nfs-ganesha.org
Ubuntu packages coming
