### ISSUE TITLE
nfs-ganesha 2.7.1, Ubuntu Bionic, missing dependency on librados2

### ISSUE THREAD

**Issue by colincoghill** [nfs-ganesha/nfs-ganesha-debian#24]
HI,

After upgrading my Ubuntu 18.04 nfs-ganesha from 2.6.3 to 2.7.1, it failed to start with:

``` Starting NFS-Ganesha file server...
bash[30915]: /usr/bin/ganesha.nfsd: error while loading shared libraries: librados.so.2: cannot open share
nfs-ganesha.service: Control process exited, code=exited status=127
nfs-ganesha.service: Failed with result 'exit-code'.
Failed to start NFS-Ganesha file server.
```

I manually `apt-get install librados2`
and now NFS-Ganesha starts.

We're running a very default config I think, maybe the built .deb's are missing the librados2 dependency?

**Comment by kalebskeithley** [comment]
bionic, cosmic, disco packages have been respun with added librados2 dependency
