### ISSUE TITLE
Why is RGW not packaged?

### ISSUE THREAD

**Issue by vlada-dudr** [nfs-ganesha/nfs-ganesha-debian#25]
Hello is there a reason why RGW support is disabled?

**Comment by kalebskeithley** [comment]
On which distribution/version?  Usually it's because the version of Ceph available in the base doesn't have a compatible API. Sometimes there's a later version of ceph in an add-on repo; if you know of such an add-on then do let us know.

**Comment by kalebskeithley** [comment]
latest 2.7.2 builds have rgw enabled if the dist has new enough ceph available
