### ISSUE TITLE
Debian packages for 2.7.2 are missing

### ISSUE THREAD

**Issue by ryno83** [nfs-ganesha/nfs-ganesha-debian#26]
Hi,
Packages for Debian are missing.
https://download.nfs-ganesha.org/2.7/LATEST/Debian/stretch/amd64/apt/
https://download.nfs-ganesha.org/2.7/2.7.2/Debian/stretch/amd64/apt/

thank you

**Comment by kalebskeithley** [comment]
packages are built by volunteers in their spare time.

There are packages there now.
