### ISSUE TITLE
Ubuntu Bionic PPA package delivers script without exec permissions

### ISSUE THREAD

**Issue by davidc0le** [nfs-ganesha/nfs-ganesha-debian#29]
We use the PPA from https://launchpad.net/~nfs-ganesha ( ppa:nfs-ganesha/nfs-ganesha-2.7 ) 

On our server, when the process is (re)started we see a (non-fatal) error about a script that cannot be executer:

Apr 26 21:39:39 SM-X10SRI4B-S-1-LDCF1-GB systemd[24860]: nfs-ganesha-config.service: Failed at step EXEC spawning /usr/lib/ganesha/nfs-ganesha-config.sh: Permission denied

The script is not delivered with execute bit set:

```
# dpkg -c nfs-ganesha_2.7.3-ubuntu1~bionic1_amd64.deb | grep nfs-ganesha-config.sh
-rw-r--r-- root/root       845 2019-04-05 13:45 ./usr/lib/ganesha/nfs-ganesha-config.sh
```

**Comment by kalebskeithley** [comment]
fixed in nfs-ganesha-2.7.3~ubuntu1-bionic2 packages
Also in xenial, cosmic, and disco
