### ISSUE TITLE
Debian package for release 2.5.0

### ISSUE THREAD

**Issue by ryno83** [nfs-ganesha/nfs-ganesha-debian#3]
Hi,
I'm installing nfs-ganesha 2.5.0 for my glusterfs 3.10 from https://download.gluster.org/pub/gluster/nfs-ganesha/2.5/2.5.0/Debian/jessie/apt/ but I modified 2 files to make it work properly for me.

* I moved `nfs-ganesha` file into `/etc/default` instead of `/etc/defaults` (without the trailing `s`).
* I modified `EnvironmentFile=-/run/sysconfig/ganesha` option in the file `/lib/systemd/system/nfs-ganesha.service` with `EnvironmentFile=/etc/default/nfs-ganesha`

I also tested the 2.4.5 and I got the same problem.

**Comment by ryno83** [comment]
I saw this morning that the debian package is upgradable to 2.5.0-2 including modifications I submited in this issue. Thank you.

But the EnvironmentFile should point to `/etc/default/nfs-ganesha`.

Thanks again

**Comment by kalebskeithley** [comment]
fixed in nfs-ganesha-2.5.0-3 packages in Ubuntu Launchpad PPA and download.gluster.org
