### ISSUE TITLE
migrate from qt4 to qt5

### ISSUE THREAD

**Issue by christmart** [nfs-ganesha/nfs-ganesha-debian#30]
qt4 is end of life and will be removed from bullseye.
the python scripts and corresponding dependencies in Debian should be fixed.

**Comment by kalebskeithley** [comment]
nfs-ganesha-2.8.2 packages for bullseye, built with pyqt5, are at https://download.nfs-ganesha.org/2.8/2.8.2/Debian/   Note: built with new style glusterfs-6.5 packages.

Also nfs-ganesha-2.8.2 packages for buster (w/ new style glusterfs-6.5, pyqt4), and stretch (old style glusterfs-6.5, pyqt4).

Any issues with the python please open an issue against nfs-ganesha itself and/or send patches to gerrithub.io.
