### ISSUE TITLE
Dependance problem with libtirpc1

### ISSUE THREAD

**Issue by Dark26dark26** [nfs-ganesha/nfs-ganesha-debian#32]
In buster with version 3.2, libtirpc1 not available. It was replace by  libtirpc-common

apt-get install nfs-ganesha
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
Certains paquets ne peuvent être installés. Ceci peut signifier
que vous avez demandé l'impossible, ou bien, si vous utilisez
la distribution unstable, que certains paquets n'ont pas encore
été créés ou ne sont pas sortis d'Incoming.
L'information suivante devrait vous aider à résoudre la situation : 

Les paquets suivants contiennent des dépendances non satisfaites :
 nfs-ganesha : Dépend: libtirpc1 mais il n'est pas installable

**Comment by kalebskeithley** [comment]
I've fixed the control files. I will respin packages over the next few days.

Thanks

**Comment by Dark26dark26** [comment]
Cool thanks.
