### ISSUE TITLE
Version Incompatibility: libntirpc-3.2 needed for nfs-ganesha (2.8 or 3.3), but only libntirpc-3.3 available

### ISSUE THREAD

**Issue by jthomme1** [nfs-ganesha/nfs-ganesha-debian#34]
Hi, I'm trying to install nfs-ganesha on ubuntu 18.04 via the ppa:
`nfs-ganesha/nfs-ganesha-3.0`.
For libntirpc I use the ppa:
`nfs-ganesha/libntirpc-3.0`.
When trying to start nfs-ganesha, I get the error message:
`/usr/bin/ganesha.nfsd: error while loading shared libraries: libntirpc.so.3.2: cannot open shared object file: No such file or directory`
The libntirpc package however installs a `libntirpc.so.3.3`.
The 2.8 version of nfs-ganesha produces the same result.
It seems that there is an incompatibility in the packages or am I doing something obvious wrong?
Also is this the right place to ask/report this?
Thanks for any help, it really is appreciated.

**Comment by kalebskeithley** [comment]
ganesha 2.8.4 needs libntirpc-1.8.1.   ganesha-3.3 needs libntirpc-3.3.  Which version of ganesha are you trying to install?

For libntirpc-1.8 and ganesha-2.8 the PPAs are ppa:nfs-ganesha/libntirpc-1.8 and ppa:nfs-ganesha/nfs-ganesha-2.8

For libntirpc-3 and ganesha-3 the PPAs are ppa:nfs-ganesha/libntirpc-3.0 and ppa:nfs-ganesha/nfs-ganesha-3.0

Make sure you're not getting the packages from the Bionic base somehow.

For questions it's probably better to just send an email to the support@lists.nfs-ganesha.org mailing list or ask for help in #ganesha on Freenode IRC.

**Comment by jthomme1** [comment]
Issuing `apt-cache policy nfs-ganesha` yields:
```
nfs-ganesha:
  Installed: 3.2-ubuntu1~bionic4
  Candidate: 3.2-ubuntu1~bionic4
  Version table:
 *** 3.2-ubuntu1~bionic4 500
        500 http://ppa.launchpad.net/nfs-ganesha/nfs-ganesha-3.0/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     2.6.0-2 500
        500 http://other-mirror.domain/ubuntu bionic/universe amd64 Packages
```
and `apt-cache policy libntirpc3`
```
libntirpc3:
  Installed: 3.3-ubuntu1~bionic1
  Candidate: 3.3-ubuntu1~bionic1
  Version table:
 *** 3.3-ubuntu1~bionic1 500
        500 http://ppa.launchpad.net/nfs-ganesha/libntirpc-3.0/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
```
As you can see, I am using the given ppas, but for some reason, nfs-ganesha-3.2 and libntirpc-3.3 get installed in different version.
I am asking this here in case some other person might have a similar problem and thus hopefully finds this thread.

**Comment by kalebskeithley** [comment]
oh, bionic. right. There's a issue building bionic packages: the linker is getting undefined references to ceph* functions in libcephfs.  It worked for ganesha 3.2 when that was built.

Unfortunately libntirpc-3.3 was already built to satisfy that dependency and there's no going back. Until I can figure out the ceph problem this repo is broken.

**Comment by kalebskeithley** [comment]
bionic packages are available now. (no ceph though.)
