### ISSUE TITLE
debian/rules copies wrong ganesha.conf

### ISSUE THREAD

**Issue by christmart** [nfs-ganesha/nfs-ganesha-debian#37]
In branch bullseye-nfs-ganesha-3
debian/rules contains

	cp src/config_samples/vfs.conf debian/tmp/etc/ganesha/ganesha.conf

but this should be

	cp src/config_samples/ganesha.conf.example debian/tmp/etc/ganesha/ganesha.conf

**Comment by kalebskeithley** [comment]
fixed in latest

new builds are in launchpad.

New packages for bullseye, buster, and stretch are on download.nfs-ganesha.org
