### ISSUE TITLE
nfs-ganesha-3 3.5-ubuntu1~xenial1 missing dependency

### ISSUE THREAD

**Issue by apunkt** [nfs-ganesha/nfs-ganesha-debian#38]
When trying to install 3.5-ubuntu1~xenial1 on

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.7 LTS"

apt responds with:

nfs-ganesha : Depends : liburcu6 but is not installable

There is no other install candidate, also not in xenial-backports.
Checking dependencies of liburc6 > libc6 (>=2.6) but xenial delivers 2.23 only.

**Comment by kalebskeithley** [comment]
fixed in 3.5-ubuntu1~xenial3
