### ISSUE TITLE
Broken dependency on libntirpc1 in Xenial (16.04)

### ISSUE THREAD

**Issue by joshbenner** [nfs-ganesha/nfs-ganesha-debian#4]
I see `libntirpc1.3` available, but nothing called `libntirpc1`

**Comment by kalebskeithley** [comment]
did you add the libntirpc repo? https://launchpad.net/~gluster/+archive/ubuntu/libntirpc-1.5

**Comment by kalebskeithley** [comment]
I believe this is fixed.
