### ISSUE TITLE
Issue for Ganesha V4 packaging - wrong install target

### ISSUE THREAD

**Issue by ffilz** [nfs-ganesha/nfs-ganesha-debian#40]
Copied from nfs-ganesha issue: https://github.com/nfs-ganesha/nfs-ganesha/issues/710

OS

Debian Buster + Backports

ISSUE TYPE

    improvement

STEPS TO REPRODUCE

    download the source package for NFS Ganesha 3.5. You need the debian directory and all dependencies.
    replace src with the content of V4-dev.58
    start to build a Debian package with dpkg-buildpackage -rfakeroot -b

WHAT HAPPEND

After compiling the install target fails. nfs-ganesha-proxy.install contains usr/lib/*-linux-gnu*/ganesha/libfsalproxy.so*

~/nfs-ganesha-4-dev.58/debian/tmp$ find -name *libfsalproxy*
./usr/lib/x86_64-linux-gnu/ganesha/libfsalproxy_v4.so
./usr/lib/x86_64-linux-gnu/ganesha/libfsalproxy_v3.so

HOW TO FIX

    Change content of nfs-ganesha-proxy.install to usr/lib/*-linux-gnu*/ganesha/libfsalproxy_v*.so

**Comment by kalebskeithley** [comment]
the *-nfs-ganesha-3 branches of the nfs-ganesha-debian repo is for building NFS-Ganesha 3.x, which doesn't have FSAL_PROXY_V3 and FSAL_PROXY_V4.

Now that ganesha 4.0 is released there are *-nfs-ganesha-4 branches in the repo which contain the necessary changes for the proxy fsals.
