### ISSUE TITLE
nfs-ganesha 4.0: no libbtrfsutil-dev dependency

### ISSUE THREAD

**Issue by linuxrrze** [nfs-ganesha/nfs-ganesha-debian#41]
Current ppa packages do not contain libbtrfsutil-dev build dependency.

Therefore the built packages do not solve the BTRFS subvol problem:

https://github.com/nfs-ganesha/nfs-ganesha/commit/3985087c985c4257a1f2acaa2a56b5499720a889

Adding this dependency in debian/control fixes the problem (tested on Ubuntu 20.04/Focal)

**Comment by kalebskeithley** [comment]
fixed in latest builds
