### ISSUE TITLE
Missing debian packages for CephFS + Rados support

### ISSUE THREAD

**Issue by Thor77** [nfs-ganesha/nfs-ganesha-debian#42]
The NFS Ganesha 4.0 repo is missing at least the packages nfs-ganesha-ceph and nfs-ganesha-rados-grace. Was this done on purpose?
It currently refuses to start with the latest nfs-ganesha package and FSAL_CEPH configured:
```
ganesha.nfsd-59561[main] load_fsal :NFS STARTUP :FATAL :Could not dlopen module: /usr/lib/x86_64-linux-gnu/ganesha/libfsalceph.so Error: /usr/lib/x86_64-linux-gnu/ganesha/libfsalceph.so: cannot open shared object file: No such file or directory. You might want to install the nfs-ganesha-CEPH package
```

**Comment by kalebskeithley** [comment]
which version of Debian?

The most likely reason is that the version of ceph in a particular Debian release is too old and doesn't have the correct API for ganesha to build the rados support

**Comment by Thor77** [comment]
@kalebskeithley Debian Bullseye, as it's the latest release it shouldn't be too old. For Ganesha 3.x the packages are present: https://download.nfs-ganesha.org/3/LATEST/Debian/bullseye/amd64/apt/pool/main/n/nfs-ganesha/

**Comment by kalebskeithley** [comment]
ceph in bullseye is ceph-14 (nautilus) . On my bullseye build machine anyway; it is up to date. Does debian have newer ceph packages in some other repo somewhere?
 
The ceph and rados APIs changed between ceph-14 and ceph-15 or ceph-16. The ganesha implementation was updated to the new APIs and won't build with the old ceph APIs in ceph-14.

**Comment by Thor77** [comment]
All Ceph releases are available for Debian in their official repository: https://download.ceph.com/debian-pacific/
https://docs.ceph.com/en/latest/install/get-packages/#configure-repositories-manually

**Comment by kalebskeithley** [comment]
We don't have the time or resources to build packages for every combinations of dependencies. We build ganesha packages with the dependencies that are officially available from Debian. The same way we do for Ubuntu, SUSE, and Fedora.
