### ISSUE TITLE
 nfs-ganesha 4.3-ubuntu1~jammy1 - depends on liburcu6, which is not in jammy

### ISSUE THREAD

**Issue by tdobes** [nfs-ganesha/nfs-ganesha-debian#43]
After adding the nfs-ganesha-4 and libntirpc-4 PPA's for Ubuntu jammy, I find that the nfs-ganesha package (version 4.3-ubuntu1~jammy1) depends on liburcu6.  However, liburcu6 is not available in Ubuntu jammy, nor is it provided in the PPA.  It appears that it's been [replaced by liburcu8](https://packages.ubuntu.com/search?keywords=liburcu&searchon=names&suite=jammy&section=all).  Perhaps the PPA should build against that version of the library if possible?  If not, perhaps the older version of the library could be included in the PPA?

**Comment by tdobes** [comment]
Upon inspecting the dependencies more closely, it appears that the package depends on *both* liburcu8 and liburcu6.  Perhaps the [inclusion of liburcu6](https://github.com/nfs-ganesha/nfs-ganesha-debian/blob/67932da518424428a28b6aef9e6598ed4f7e25fc/debian/control#L55) is an error?

```Package: nfs-ganesha
Priority: optional
Section: net
Installed-Size: 1865
Maintainer: Gluster Packager <glusterpackager@download.gluster.org>
Architecture: amd64
Version: 4.3-ubuntu1~jammy1
Depends: dbus, nfs-common, rpcbind, libacl1 (>= 2.2.23), libblkid1 (>= 2.16), libbtrfsutil1 (>= 5.6), libc6 (>= 2.34), libcap2 (>= 1:2.10), libcom-err2 (>= 1.43.9), libdbus-1-3 (>= 1.9.14), libgssapi-krb5-2 (>= 1.17), libkrb5-3 (>= 1.6.dfsg.2), libnfsidmap1 (>= 1:2.6.1), libntirpc4 (>= 4.3), liburcu8 (>= 0.13.0), libuuid1 (>= 2.16), libwb
client0 (>= 2:4.0.3+dfsg1), liburcu6, libtirpc3, daemon
Filename: pool/main/n/nfs-ganesha/nfs-ganesha_4.3-ubuntu1~jammy1_amd64.deb
Size: 684350
MD5sum: e951bf10785661ff8374d6f9aa5ad140
SHA1: 35dfd72100794a7330f9b0d36680049c4dee22d9
SHA256: 53c7384636f2a751766f01212313d9a3ed77a37acd551541aea19d85c5cfb54e
Description-en: NFS server in User Space
 NFS-GANESHA is a NFS Server running in user space with a large cache.
 It comes with various backend modules to support different file systems
 and namespaces. Supported name spaces are POSIX, PROXY, SNMP, FUSE-like,
 HPSS, LUSTRE, XFS and ZFS.
 .
 This package contains the binaries.
Description-md5: 429c1c3b60dd148f6a4a5f902ffab206```

**Comment by kalebskeithley** [comment]
fixed
