### ISSUE TITLE
Does libntirpc4 (>= 5.0) exist?

### ISSUE THREAD

**Issue by mjsf12** [nfs-ganesha/nfs-ganesha-debian#44]
I am trying to install NFS Ganesha 5 on Ubuntu 22.04 (container) using these PPAs:
https://launchpad.net/~nfs-ganesha/+archive/ubuntu/nfs-ganesha-5
https://launchpad.net/~nfs-ganesha/+archive/ubuntu/libntirpc-5

However, I receive this error message when I try to install it:

```
The following packages have unmet dependencies:

 nfs-ganesha : Depends: libntirpc4 (>= 5.0) but it is not installable

E: Unable to correct problems, you have held broken packages.

building at STEP "RUN apt install tini nfs-ganesha libntirpc5 nfs-ganesha-vfs nfs-ganesha-proxy-v4 nfs-ganesha-vfs -y": while running runtime: exit status 100
```
I noticed that libntirpc4 only goes up to version 4.3, and libntirpc5 is for version 5.0, but it is not a dependency of nfs-ganesha 5.

Alternatively, I tried downloading version 5 of nfs-ganesha from https://download.nfs-ganesha.org/, but I could not find any binaries available for it.

I apologize for any mistakes, English is not my first language and this has been reviewed by ChatGPT.

**Comment by kalebskeithley** [comment]
it should be Depends: libntirpc5 (>= 5.0)

fixed
