### ISSUE TITLE
NTIRPC_1.5.3 not found

### ISSUE THREAD

**Issue by ryno83** [nfs-ganesha/nfs-ganesha-debian#8]
After upgrade from 2.5.0-2 to 2.5.0-5, nfs-ganesha won't start because it needs libntirpc 1.5.3. The version 1.5.2 was install on my system. The nfs-ganesha should look for this dependancy version. An `apt-get install libntirpc1` fix it !
Thank you

**Comment by kalebskeithley** [comment]
I believe this is fixed in later releases, e.g. 2.5.2 or 2.5.3. If somehow it's not, please open a new issue against the newer version.
